services:
  database:
    image: 'postgres:17.2-alpine3.21'
    env_file:
      - './.env.development'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      target: dev
    env_file:
      - './.env.development'
      - './apps/backend/.env'
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - '3001:3001'
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src
      - ./apps/backend/drizzle.config.ts:/usr/src/app/apps/backend/drizzle.config.ts
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3001/status']
      interval: 10s
      timeout: 5s
      retries: 3
